### ISSUE TITLE
Access denied, please inspect WWW-Authenticate header

### ISSUE THREAD

**Issue by CodeWolf86** [Azure-Samples/Azure-Maps-AzureAD-Samples#5]
Hi There,

I've been trying the OpenIdConnectSample but get the following error when loading the map:

`{
  "error": {
    "code": "Unauthorized",
    "message": "Access denied, please inspect WWW-Authenticate header.",
    "target": null,
    "details": []
  }
}
`
Checking out the master branch of the samples. The only changes I've made in the OpenIdConnect/AzureMapsOpenIdConnectV1 codebase are:

- Modifying AzureAdOption.cs 
  - Updating the ClientId & Tenant Id to my respective Tenant
  - To test initial working I commented out the key vault key retrieval and hard coded my setup secret to simplify the solution that I run locally
- Modifying VIews/Maps/Index.cshtml with the ClientID of my App Registration in my subscription.

The App loads, retrieves a token correctly but then when it attempts to load the map, all of the tiles return a 401 with the above error. I believe i've setup all of the app registration side correctly as it woudn't let it retrieve the token otherwise. Token attached below. Any ideas?

`{
  "aud": "https://atlas.microsoft.com/",
  "iss": "https://sts.windows.net/922b2f31-c0b5-401d-beb7-b2de2e4bb274/",
  "iat": 1596037862,
  "nbf": 1596037862,
  "exp": 1596041762,
  "acr": "1",
  "aio": "AUQAu/8QAAAAVRr7IetliJDyH4InMCVUaWRfVla0vXrsZ1ml8TDxMpZTpMbaRngwWIgpzXqsofguiwr2p5+IwuWm+McW7abupg==",
  "altsecid": "1:live.com:000340011DAF5551",
  "amr": [
    "pwd"
  ],
  "appid": "<redacted>",
  "appidacr": "1",
  "email": "<redacted>",
  "family_name": "<redacted>",
  "given_name": "<redacted>",
  "groups": [
    "763dcd68-5a8f-43e6-8c59-31572bb929a5"
  ],
  "idp": "live.com",
  "ipaddr": "31.51.191.176",
  "name": "<redacted>",
  "oid": "37ea4a95-dc35-4b8d-9291-5ce4c3288deb",
  "puid": "100320009AFA0721",
  "scp": "user_impersonation",
  "sub": "T-hjRsm0ldBhG34QtjxF83G6V6toh2L5xv0y7K9eiRQ",
  "tid": "922b2f31-c0b5-401d-beb7-b2de2e4bb274",
  "unique_name": "<redacted>",
  "uti": "5ljDW6caSE62tgZp4DDVAA",
  "ver": "1.0",
  "wids": [
    "62e90394-69f5-4237-9190-012177145e10"
  ]
}`

**Comment by stack111** [comment]
Hi @CodeWolf86,
I'll need a bit more information to help you effectively. What is the value of the WWW-Authenticate header? You should be able to use any browser developer tools to inspect this response header. You could also copy the request and use it in Postman or Fiddler to inspect the header.

Regarding OpenIdConnectV1 sample - this corresponds to documentation [to setup for a web application](https://docs.microsoft.com/en-us/azure/azure-maps/how-to-secure-webapp-users). There maybe a step which may have been missed. 

Looking at the token, it appears the principal is issued from live.com (which is likely the issue). I don't have the token header but I would check to see if the `kid` value matches one of the public keys `kid` values at the public v1 discovery endpoint [https://login.microsoftonline.com/common/discovery/keys](https://login.microsoftonline.com/common/discovery/keys) 

{
  "aud": "https://atlas.microsoft.com/",
  "iss": "https://sts.windows.net/922b2f31-c0b5-401d-beb7-b2de2e4bb274/",
  "iat": 1596037862,
  "nbf": 1596037862,
  "exp": 1596041762,
  **"altsecid": "1:live.com:000340011DAF5551",**
  "groups": [ "763dcd68-5a8f-43e6-8c59-31572bb929a5" ],
  **"idp": "live.com",**
  "oid": "37ea4a95-dc35-4b8d-9291-5ce4c3288deb",
  "puid": "100320009AFA0721",
  "scp": "user_impersonation",
  "tid": "922b2f31-c0b5-401d-beb7-b2de2e4bb274",
}

It's likely the sign in is from a personal account instead of an organizational account. As an example typically an organizational account token looks like below. Note: the kid value matches one of the public keys and the idp is from an Azure AD tenant - not live.com.
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "huN95IvPfehq34GzBDZ1GXGirnM",
  **"kid": "huN95IvPfehq34GzBDZ1GXGirnM"**
}.{
  "aud": "https://atlas.microsoft.com/",
  "iss": "https://sts.windows.net/<redacted>/",
  "iat": 1596123503,
  "nbf": 1596123503,
  "exp": 1596127403,
  "acr": "1",
  "aio": "AXQAi/8QAAAAxmx7ObktUs+CFd346F0g0/ucv0kjG9gFXnzUWJEjuDiyPmL/c7HxRiQDjPiLrHeXHeS7MAPJQLQei+hzF0MV7jGjE+orLuJXOwFOKgT27vGgyrESFjNRkGo09d4Y/vo4GzoA+H8UwNBJArAUFE2qDw==",
  **"altsecid": "5::10037FFE84502CE5",**
  "amr": [
    "rsa"
  ],
  "appid": "<redacted>",
  "appidacr": "1",
  "email": "<redacted>",
  "family_name": "<redacted>",
  "given_name": "<redacted>",
  "groups": [
     "<redacted>"
  ],
  **"idp": "https://sts.windows.net/<redacted>/",**
  "ipaddr": "<redacted>",
  "name": "<redacted>",
  "oid": "20a99c47-a546-4465-be71-cfc84e934eca",
  "puid": "<redacted>",
  "scp": "user_impersonation",
  "sub": "<redacted>",
  "tid": "<redacted>",
  "unique_name": "<redacted>",
  "uti": "<redacted>",
  "ver": "1.0",
  "wids": [
    "<redacted>"
  ]
}.[Signature]

**Comment by CodeWolf86** [comment]
Hi @stack111 

Thank you for the response. You are correct the token was issued from a live.com account rather than an organisational account. I wasn't aware of this requirement being a limitation of azure maps so thank you for bringing it to my attention.

My problem was even when inspecting via fiddler the `WWW-Authenticate header` wasn't supplied but it looks like this was a result of not using an organisational account, as now I've switched to one, the header is also still not being sent so may have been a red herring.

With the switch to the organisation account I have now got the samples working. Thanks!
